# ============================================================
# Telegram Server Bot
# Default Configuration
#
# 此文件属于程序默认值
# 不建议修改
# ============================================================


# 项目路径

TG_ROOT="/opt/tg_bot"

APP_DIR="/opt/tg_bot/app"

DATA_DIR="/opt/tg_bot/data"

LOG_DIR="/opt/tg_bot/logs"



# 默认历史保存

METRICS_DAYS=7


# 默认消息长度

MESSAGE_LIMIT=3900


# 默认检测端口

MIHOMO_SCAN_PORTS="9090 9097 9999"


